// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACfMupdcXlozed4uvYALbRpap9ld_5YCo',
    appId: '1:395242694969:web:1b970b2abc56683f6020e8',
    messagingSenderId: '395242694969',
    projectId: 'stream-quiz-app-dev',
    authDomain: 'stream-quiz-app-dev.firebaseapp.com',
    storageBucket: 'stream-quiz-app-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTKY28y_7PFubPDECqf9UdKDq7UAJ0ge8',
    appId: '1:395242694969:android:485e5c347ff853086020e8',
    messagingSenderId: '395242694969',
    projectId: 'stream-quiz-app-dev',
    storageBucket: 'stream-quiz-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAId2q5N-HBegtv90UXv_L9OgAjwDgun5o',
    appId: '1:395242694969:ios:66ce2450549c33b56020e8',
    messagingSenderId: '395242694969',
    projectId: 'stream-quiz-app-dev',
    storageBucket: 'stream-quiz-app-dev.appspot.com',
    iosClientId: '395242694969-m7mkuqmudbms20fhi9cu7270jfh9foom.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAId2q5N-HBegtv90UXv_L9OgAjwDgun5o',
    appId: '1:395242694969:ios:66ce2450549c33b56020e8',
    messagingSenderId: '395242694969',
    projectId: 'stream-quiz-app-dev',
    storageBucket: 'stream-quiz-app-dev.appspot.com',
    iosClientId: '395242694969-m7mkuqmudbms20fhi9cu7270jfh9foom.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamQuizApp',
  );
}
